import type { KnowledgeArticle } from "./types";

export const configuringSpfDkimDmarc: KnowledgeArticle = {
  slug: "configuring-spf-dkim-dmarc-and-email-aliases",
  title: "Configuring SPF, DKIM, DMARC and Email Aliases",
  category: "Knowledge Base",
  goal: "Implement authenticated email for a custom domain hosted in Hostinger using Zoho Mail.",
  steps: [
    "Verify domain in Zoho Mail.",
    "Add Zoho MX records in Hostinger.",
    "Add SPF TXT record: v=spf1 include:zohomail.com ~all (TTL 14400).",
    "Publish DKIM TXT record generated by Zoho.",
    "Publish DMARC TXT record.",
    "Create aliases: hello@, jobs@, projects@, security@.",
    "Validate with MXToolbox and test mail flow.",
  ],
  validationChecklist: [
    "MX resolves",
    "SPF published",
    "DKIM published",
    "DMARC published",
    "Mail sends",
    "Mail receives",
    "Aliases deliver",
  ],
  references: ["Zoho Mail Admin", "Hostinger DNS Zone Editor", "MXToolbox"],
  relatedProjectSlug: "professional-email-infrastructure",
};
